# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: linux-64
name: option3

channels:
  - conda-forge

dependencies:
  - pip
  - python=3.7

  - pip:
    - -r file:requirements.txt
